"""workout

Revision ID: b7c8de3eb691
Revises: 7491e9c30abf
Create Date: 2025-08-30 23:04:27.865686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c8de3eb691'
down_revision = '7491e9c30abf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
